### ISSUE TITLE
ASDK

### ISSUE THREAD

**Issue by vadymmarkov** [hyperoslo/Wall#2]
Would be nice to use this one https://github.com/facebook/AsyncDisplayKit. I think it shouldn't be a requirement, but we could add an property like `useNodes` in `WallController`, then `ASCollectionView` will be used instead of `UICollectionView`. The only disadvantage is having a new dependency.
What do you think @zenangst ?

**Comment by zenangst** [comment]
I like this! 👍

**Comment by zenangst** [comment]
Adding dependencies is not a bad thing as long as it adds something, `AsyncDisplayKit` seems like it could bring something to the table!

I would love to see what this would look like in a pull request :sunglasses:

**Comment by vadymmarkov** [comment]
Yeah, I like how you can make dynamically-sized cells with `AsyncDisplayKit`, and there are some performance benefits. Will play with it and make a pully :hand:

**Comment by zenangst** [comment]
@vadymmarkov have I told you that it's great to have you on the team, I probably have! 😎
