### ISSUE TITLE
Rename Attachment to Media

### ISSUE THREAD

**Issue by vadymmarkov** [hyperoslo/Wall#46]
I think the name `Media` is more suitable for content types we have like images and videos.
What do you guys think @zenangst @richardoti ?

**Comment by zenangst** [comment]
I thought `Attachment` was kind of suitable in this case. If you think about it like email, you add all external resources to an email as attachments.

What if you want to attach a task to a post and display it like an inline check list or a quiz? Then it's not really media anymore.

I might be wrong here :sunglasses: 

What do you think @richardoti ?

**Comment by vadymmarkov** [comment]
Now `Attachment` is a `protocol` with `var thumbnail: URLStringConvertible { get }`, so it's supposed to return a thumbnail url of some image. And attachment is something nice to have, but it's kind of different. But I might be wrong :smiley:

**Comment by richardoti** [comment]
As for me - no difference, unless everybody knows, what it is.
"Media" is a more narrow specification, so if we sure, that there will not be any other attachment types, we can go with that.
