### ISSUE TITLE
Improve configuration / customization

### ISSUE THREAD

**Issue by vadymmarkov** [hyperoslo/Wall#60]
What we have now is the set of default `nodes` like `PostCellNode`, `PostHeaderNode`, `AttachmentNode`, etc. And also we have a lot of configuration options in `Config`. But what if you need to have different kind of layout, like custom attachments gallery, show the text at the top and post date at the bottom, or even add some new node in the the hierarchy of post views. `Config` can't cover everyone's needs, so the idea is to have something more flexible. Any thoughts @zenangst @richardoti ?

**Comment by richardoti** [comment]
What do you think about doing it as Collection/Table view? so you could register class for some kind of cell and then work with that cell?

**Comment by vadymmarkov** [comment]
@zenangst @RamonGilabert @richardoti 
It's not merged yet https://github.com/hyperoslo/Wall/pull/77, but if you like the idea, all the classes like `PostHeaderNode`, `PostFooterNode`, `AttachmentGridNode` could be created in the same way, so we have Type properties for every node in the config. Then we could move all the customization properties from the config to specific class properties. 
1) The good thing - config becomes tiny.
2) The bad thing - to customise something you have to extend node classes and override properties like text color, font (or just create your fully custom class with no inheritance) and then `register` you class type in the config like: 
`config.wall.post.HeaderClass = MyHeaderNode.self`

What do you guys think?

**Comment by vadymmarkov** [comment]
@zenangst @RamonGilabert @richardoti Could you check my comment before we close it? :smiley:

**Comment by zenangst** [comment]
@vadymmarkov that works for me! having a huge configuration could quickly become a nightmare.

**Comment by vadymmarkov** [comment]
@zenangst Then let's give it a try.

**Comment by richardoti** [comment]
@vadymmarkov Haven't seen your last post, but I've checked the PR before, I like the idea.
