### ISSUE TITLE
Model protocols - step 2

### ISSUE THREAD

**Issue by vadymmarkov** [hyperoslo/Wall#74]
@zenangst @RamonGilabert 
Trapped to hell with implementation of new `Wall` protocols in `Realm` models. For example in `Post` there is property  `public dynamic var author: User?`, but I can’t make it `public dynamic var author: Profileable?`, because `Realm` expects some concrete class extended from `Object` as relation.

I see 3 ways to solve it:
1. Prefix all Wall protocol methods with `wall`, like `protocol Postable { var wallAuthor: Profileable }`. Don’t really like it.
2. Go with the second way I proposed, like `protocol Postable { var post: Post }`.
3. Go without protocols at all, so we always waiting for Wall.Post objects in WallController, and then we do manual conversion from Realm `Post` to `Wall.Post` in the project.

2 and 3 options are quite the same, the only difference is that in the option 2 we do this conversion in the project and pass array of `Wall.Post` objects to `WallController`, and in the option 3 we receive an array of `Postable` objects in `WallController` and then extract `Wall.Post` from the each.

**Comment by zenangst** [comment]
I think I favor option 2. It would be nice if the Wall component handled the conversion so that you don't have to do that in all the projects where you are gonna use it. @vadymmarkov @RamonGilabert what do you guys think?

**Comment by vadymmarkov** [comment]
Under conversion I mean something like `let wallPosts = posts.map { $.post }`.

**Comment by zenangst** [comment]
@vadymmarkov Yeah but it's one less step for the application implementation right?

**Comment by vadymmarkov** [comment]
@zenangst Ok, let's try it. Then the name `PostConvertible` makes more sense than `Postable`.
What do you think if we add this `wall` prefix, I guess it's more descriptive to write `post.wallPost`, or maybe the name of a var should be `postConvertible`, then `postConvertible.post` doesn't look too bad. And what do you think about using of `func` instead of var, like `toWallPost`
```swift
// 1. - post.toWallPost()
protocol PostConvertible {
  func toWallPost() -> Post
}

// 2. - post.wallPost
protocol PostConvertible {
  var wallPost: Post
}

// 3. - postConvertible.toPost()
protocol PostConvertible {
  func toPost() -> Post 
  var post: Post // postConvertible.post
}

// 4. - postConvertible.post
protocol PostConvertible {
  var post: Post 
}
```

**Comment by RamonGilabert** [comment]
I'd also go for way 2, then the conversions and all that stuff happens before and not in the wall. Sorry to be late, just got the email of the discussion.

**Comment by zenangst** [comment]
@vadymmarkov For me, `3.` looks best, what do you think?

**Comment by vadymmarkov** [comment]
I made mistake in 3 :smiley: Do you mean use it like `postConvertible.toPost()`? Like it too.

**Comment by zenangst** [comment]
All good things come in `3`. :sunglasses:
